timeout: 2400s
options:
  substitution_option: ALLOW_LOOSE
steps:
  - name: 'gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20211118-2f2d816b90'
    entrypoint: make
    env:
    - TAG=$_GIT_TAG
    - BASE_REF=$_PULL_BASE_REF
    - DOCKER_CLI_EXPERIMENTAL=enabled
    args:
    - release-staging
    # default cloudbuild has HOME=/builder/home and docker buildx is in /root/.docker/cli-plugins/docker-buildx
    # set the home to /root explicitly to if using docker buildx
    - HOME=/root
substitutions:
  # _GIT_TAG will be filled with a git-based tag for the image, of the form vYYYYMMDD-hash, and
  # can be used as a substitution
  _GIT_TAG: '12345'
  _PULL_BASE_REF: 'dev'
